name: ambientguard
description: Privacy-Risiken in physischen Räumen transparent und lokal einschätzen.
publish_to: "none"
version: 0.2.0+4

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_reactive_ble: ^5.5.0
  mobile_scanner: ^7.4.2
  permission_handler: ^13.0.2
  wifi_scan: ^0.5.0
  shared_preferences: ^2.5.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
